version: '3.7'

services:
  auth_db:
    image: 'postgres:14-alpine'
    container_name: auth_db
    user: root
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
#    volumes:
#      - ./volumes/db/auth:/var/lib/postgresql/data
    restart: on-failure
  auth:
    image: vadim2422/foco_auth
    container_name: auth
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth_db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - auth_db
    restart: on-failure
    ports:
      - "8085:8080"

