version: '3.7'

services:
  postgres_foco:
    image: postgres:14
    container_name: postgres_foco
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./volumes/db/auth:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "8084:5432"

  auth:
    image: vadim2422/foco_auth

    container_name: auth
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres_foco/db"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - postgres_foco
    restart: on-failure
    ports:
      - "8085:8080"

