version: '3'

services:
  postgresql:
    container_name: postgresql
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "8083:5432"
    restart: always
    networks:
      - app-network
  app:
    image: vadim2422/foco_auth
    container_name: foco_auth
    ports:
      - "8081:8080"
    depends_on:
      - postgresql
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge